# requirements.yml

python: 3.12.12
packages:
  numpy==1.26.4
  scipy==1.13.1
  pandas==2.3.3
  matplotlib==3.10.7
  astropy==7.1.1
  numba==0.62.1
  shapely==2.1.2
  tqdm==4.67.1
  ebltable==0.6.3
  emcee==3.1.6
  corner==2.2.3

